### ISSUE TITLE
Add ARG

### ISSUE THREAD

**Issue by Jrmy2402** [Seikho/node-dockerfile#4]
Hi

Thanks for this module, it works well.

however, the element ARG is missing. Is it possible to add it?

Thanks again!

**Comment by Seikho** [comment]
Done and published in `v0.6.0`

**Comment by Jrmy2402** [comment]
Thanks for adding ARG but we have an error now : 
TypeError: Builder is not a constructor

`var Builder = require("node-dockerfile");

var dockerFile = new Builder();
     // Let's just add in a bunch of funky commands for a bit of fun
      dockerFile
        .from("node:0.12.4")
        .newLine()
        .comment("Clone and install dockerfile")
        .run([
          "apt-get install -y git",
          "git clone https://github.com/seikho/node-dockerfile /code/node-dockerfile"
        ])`

**Comment by Seikho** [comment]
If you're using TypeScript to ES6 module syntax:
`import { Builder } from 'node-dockerfile'`
CommonJS:
`const Builder = require('node-dockerfile').Builder`

**Comment by Jrmy2402** [comment]
TY again, you forget a return in index.ts

 `    Builder.prototype.arg = function (key, value) {
        this.instructions.push(makeInstruction("ARG", key + "=" + (value || '')));
        return this;
    };`

**Comment by Seikho** [comment]
Woops! Sorry about that. Fixed in `v0.6.2` 😄
